USE Food_App_Project;
GO
-- PHASE 1 — EXPLORATORY ANALYSIS

-- 1. Total revenue generated by the food delivery app 
SELECT SUM(order_amount - discount) AS total_revenue FROM orders$;

-- 2. Total orders per city 
SELECT r.city, COUNT(*) AS total_orders
FROM orders$ o
JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

-- 3. Top 10 Restaurants
SELECT TOP 10 r.restaurant_name, r.city, SUM(o.order_amount - o.discount) AS total_revenue
FROM orders$ o
JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name, r.city
ORDER BY total_revenue DESC;


--PHASE 2 - CUSTOMER SEGMENTATION

-- 4. Customer Category (Gold/Silver/Bronze) based on total spending
SELECT 
    o.customer_id,
    SUM(o.order_amount - o.discount) AS total_spent,
    CASE 
        WHEN SUM(o.order_amount - o.discount) >= 50000 THEN 'Gold'
        WHEN SUM(o.order_amount - o.discount) >= 10000 THEN 'Silver'
        ELSE 'Bronze'
    END AS customer_category
FROM orders$ o
GROUP BY o.customer_id
ORDER BY total_spent DESC;

-- PHASE 3 — RESTAURANT PERFORMANCE

--5. Top 10 restaurants by revenue
SELECT TOP 10
r.restaurant_name,
r.restaurant_id,
r.city,
SUM(o.order_amount - o.discount) AS total_revenue
FROM orders$ o
JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name, r.restaurant_id, r.city
ORDER BY total_revenue DESC;

--6. Average rating vs Revenue
SELECT r.restaurant_name, r.rating, SUM(o.order_amount - o.discount) AS total_revenue
FROM orders$ o
JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name, r.rating
ORDER BY total_revenue DESC;

-- pHASE 4 — DELIVERY ANALYSIS

-- 7. Average delivery time per city
SELECT r.city, AVG(o.delivery_time) AS avg_delivery_time 
FROM orders$ o
JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY avg_delivery_time ASC; 

-- 8. Late delivery(Above 45 Minutes)
SELECT r.city, COUNT(*) AS late_deliveries
FROM orders$ o
JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
WHERE o.delivery_time > 45
GROUP BY r.city
ORDER BY late_deliveries DESC;

-- PHASE 5 PAYMENT & DISCOUNT ANALYSIS

-- 9. Payment method distribution
SELECT payment_method, COUNT(*) AS count
FROM orders$
GROUP BY payment_method
ORDER BY count DESC;

-- 10. Discount impact on revenue
SELECT
    discount,
    COUNT(*) AS total_orders,
    SUM(order_amount - discount) AS revenue_after_discount
FROM orders$
GROUP BY discount
ORDER BY discount;

-- PHASE 6 - ADVANCE SQL 

-- 11. Monthly revenue using CTE
WITH MonthlyRevenue AS (
    SELECT 
        month(order_date) AS month,
        SUM(order_amount - discount) AS revenue
    FROM orders$
    GROUP BY month(order_date)
)
SELECT month, revenue
FROM MonthlyRevenue
ORDER BY month;

-- 12. Rank Restaurants by Revenue (Window Function)
SELECT
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue,
    RANK() OVER (ORDER BY SUM(o.order_amount - o.discount) DESC) AS revenue_rank
FROM orders$ o
JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name;

-- 13. Above Average Revenue Restaurants (Subquery)
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM orders$ o
JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
HAVING SUM(o.order_amount - o.discount) > (
    SELECT AVG(order_amount - discount) FROM orders$
);

-- PHASE 7 — DATABASE OBJECTS

-- 14. Create revenue view 
GO
DROP VIEW IF EXISTS revenue_view;
GO
CREATE VIEW revenue_view AS
SELECT 
r.restaurant_id,
r.restaurant_name,
r.city,
SUM(o.order_amount - o.discount) AS total_revenue
FROM orders$ o
JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city;
GO

-- 15. Stored Procedure: Get Top N Restaurant
GO
DROP PROCEDURE IF EXISTS GetTopNRestaurants;
GO
CREATE PROCEDURE GetTopNRestaurants
    @TopN INT
AS
BEGIN
    SELECT TOP (@TopN)
    r.restaurant_id,
    r.restaurant_name,
    r.city,
    SUM(o.order_amount - o.discount) AS total_revenue
    FROM orders$ o
    JOIN restaurants$ r ON o.restaurant_id = r.restaurant_id
    GROUP BY r.restaurant_id, r.restaurant_name, r.city
    ORDER BY total_revenue DESC;
END;
GO

-- PHASE 8-- PERFORMANCE OPTIMIZATION

-- 16. Index on order_date (for monthly reports)
CREATE INDEX idx_order_date ON orders$(order_date);

-- 17. Index on customer_id (for joins)
CREATE INDEX idx_customer_id ON customer(customer_id);

-- 18. Index on restaurant_name
CREATE INDEX idx_restaurant_name ON restaurants$(restaurant_name);

-- PHASE 9 — AUTOMATION LOGIC

-- Auto log high value orders
CREATE TABLE HighValueOrdersLog (
    log_id INT PRIMARY KEY IDENTITY(1,1),
    order_id INT,
    customer_id INT,
    order_amount DECIMAL(10,2),
    log_date DATETIME DEFAULT GETDATE()
);
GO  
-- using SQL Server syntax 
CREATE TRIGGER dbo.trg_HighValueOrder
ON dbo.orders$
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.HighValueOrdersLog (order_id, customer_id, order_amount)
    SELECT i.order_id, i.customer_id, i.order_amount - i.discount
    FROM inserted AS i
    WHERE i.order_amount - i.discount > 1000; 
END;
GO

INSERT INTO orders$ VALUES (1010, 231, 138, '2024-01-01', 1200.00, 100.00, 'Credit Card', 30);
INSERT INTO orders$ VALUES (1011, 232, 139, '2024-01-02', 8000.00, 50.00, 'Cash', 25);
GO

-- 19. Create Trigger for Prevent Negative Discount
DROP TRIGGER IF EXISTS dbo.trg_PreventNegativeDiscount;
GO
CREATE TRIGGER trg_PreventNegativeDiscount
ON [orders$]
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM inserted WHERE discount < 0)
    BEGIN
        RAISERROR ('Discount cannot be negative', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;

  INSERT INTO orders$ VALUES (1014, 231, 138, '2024-01-03', 500.00, -20.00, 'UPI', 20);

  SELECT * FROM orders$ where order_id = 1014;

  -- 20. Triggger for Delivery Delay Warning
  CREATE TABLE DeliveryDelayLog (
    log_id INT PRIMARY KEY IDENTITY(1,1),
    order_id INT,
    customer_id INT,
    restaurant_id INT,
    delivery_time INT,
    created_at DATETIME DEFAULT GETDATE()
);
GO

-- SQL Server trigger: use the inserted table and set-based insert
CREATE TRIGGER dbo.logLateDeliveries
ON dbo.orders$
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.DeliveryDelayLog (order_id, customer_id, restaurant_id, delivery_time)
    SELECT i.order_id, i.customer_id, i.restaurant_id, i.delivery_time
    FROM inserted AS i
    WHERE i.delivery_time > 45;
END;
GO

INSERT into orders$ VALUES (1016, 231, 138, '2024-01-04', 600.00, 30.00, 'Credit Card', 55);

